services:
  data_preparation:
    # build: 
      # context: ./data/
    image: ${IMAGE_REGISTRY}.dkr.ecr.${REGION}.amazonaws.com/data_preparation
    volumes:
      - ./data/initial_format:/app/initial_format
      - ./data/parquet_format:/app/parquet_format
    environment:
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
    restart: 'no'
  jar_files_preparation:
    # build:
      # context: ./Spark_ETL/jar_files/
    image: ${IMAGE_REGISTRY}.dkr.ecr.${REGION}.amazonaws.com/jar_files_preparation
    volumes:
      - ./Spark_ETL/jar_files:/app/jar_files
    restart: 'no'
    depends_on:
      data_preparation:
        condition: service_completed_successfully
  tests:
    # build:
      # context: ./Spark_ETL/
    image: ${IMAGE_REGISTRY}.dkr.ecr.${REGION}.amazonaws.com/tests
    environment:
      GEOCODE_KEY: ${GEOCODE_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      PYARROW_IGNORE_TIMEZONE: 1
    depends_on:
      data_preparation:
        condition: service_completed_successfully
    command: spark-submit ../test/test.py
  app:
    # build:
      # context: ./Spark_ETL/
    image: ${IMAGE_REGISTRY}.dkr.ecr.${REGION}.amazonaws.com/app
    volumes:
      - ./Spark_ETL/jar_files:/opt/jar_files
      - ./data/initial_format:/opt/data/initial_format
      - ./data/parquet_format:/opt/data/parquet_format
    restart: 'no'
    environment:
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      GEOCODE_KEY: ${GEOCODE_KEY}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
    depends_on:
      tests:
        condition: service_completed_successfully
    command: ./start_app_within_container.sh